plugins { id 'com.android.application' version '8.6.1' }
def versionProps = new Properties()
rootProject.file('../version.properties').withInputStream { versionProps.load(it) }
android {
    namespace 'com.izzy.twa'
    compileSdk 35
    defaultConfig {
        applicationId 'com.izzy.twa'
        minSdk 24
        targetSdk 35
        versionName versionProps.getProperty('versionName')
        versionCode versionProps.getProperty('versionCode').toInteger()
    }
    buildTypes {
        debug { applicationIdSuffix '.debug' }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures { buildConfig true }
}
dependencies { implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0' }
